# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_files/mask_creation.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Masking_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(360, 300)
        Dialog.setWindowTitle("Создание маски")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.text_instructions = QtWidgets.QTextBrowser(Dialog)
        self.text_instructions.setObjectName("text_instructions")
        self.verticalLayout.addWidget(self.text_instructions)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")

        self.label_x_max = QtWidgets.QLabel(Dialog)
        self.label_x_max.setObjectName("label_x_max")
        self.gridLayout_2.addWidget(self.label_x_max, 0, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 4, 1, 1)

        self.label_x_min = QtWidgets.QLabel(Dialog)
        self.label_x_min.setObjectName("label_x_min")
        self.gridLayout_2.addWidget(self.label_x_min, 0, 1, 1, 1)

        self.label_x = QtWidgets.QLabel(Dialog)
        self.label_x.setObjectName("label_x")
        self.gridLayout_2.addWidget(self.label_x, 1, 2, 1, 1)

        self.enter_x_left = QtWidgets.QDoubleSpinBox(Dialog)
        self.enter_x_left.setDecimals(1)
        self.enter_x_left.setProperty("value", 0.0)
        self.enter_x_left.setObjectName("enter_x_left")
        self.gridLayout_2.addWidget(self.enter_x_left, 1, 1, 1, 1)

        self.enter_x_right = QtWidgets.QDoubleSpinBox(Dialog)
        self.enter_x_right.setDecimals(1)
        self.enter_x_right.setObjectName("enter_x_right")
        self.gridLayout_2.addWidget(self.enter_x_right, 1, 3, 1, 1)

        self.verticalLayout.addLayout(self.gridLayout_2)

        self.line = QtWidgets.QFrame(Dialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")

        self.enter_y_bottom = QtWidgets.QDoubleSpinBox(Dialog)
        self.enter_y_bottom.setDecimals(1)
        self.enter_y_bottom.setSingleStep(0.1)
        self.enter_y_bottom.setProperty("value", 0.0)
        self.enter_y_bottom.setObjectName("enter_y_bottom")
        self.gridLayout.addWidget(self.enter_y_bottom, 3, 1, 1, 1)

        self.label_y_min = QtWidgets.QLabel(Dialog)
        self.label_y_min.setObjectName("label_y_min")
        self.gridLayout.addWidget(self.label_y_min, 2, 1, 1, 1)

        self.label_y = QtWidgets.QLabel(Dialog)
        self.label_y.setObjectName("label_y")
        self.gridLayout.addWidget(self.label_y, 3, 2, 1, 1)

        self.label_y_max = QtWidgets.QLabel(Dialog)
        self.label_y_max.setObjectName("label_y_max")
        self.gridLayout.addWidget(self.label_y_max, 2, 3, 1, 1)

        self.enter_y_top = QtWidgets.QDoubleSpinBox(Dialog)
        self.enter_y_top.setDecimals(1)
        self.enter_y_top.setObjectName("enter_y_top")
        self.gridLayout.addWidget(self.enter_y_top, 3, 3, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 2, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 2, 4, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)

        self.button_preview = QtWidgets.QPushButton(Dialog)
        self.button_preview.setObjectName("button_preview")
        self.verticalLayout.addWidget(self.button_preview)

        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        self.text_instructions.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Cantarell\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Выбор границ прямоугольной области, которая будет использована в дальнейших шагах.</p></body></html>"))
        self.label_x_max.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">max</p></body></html>"))
        self.label_x_min.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">min</p></body></html>"))
        self.label_x.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"> ≤ x ≤ </p></body></html>"))
        self.label_y_min.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">min</p></body></html>"))
        self.label_y.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">≤ y ≤ </p></body></html>"))
        self.label_y_max.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">max</p></body></html>"))
        self.button_preview.setText(_translate("Dialog", "Предпросмотр"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Masking_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
